import type { Metadata } from "next";

const SITE = "https://www.aiagentforge.in";

export const metadata: Metadata = {
  title: {
    absolute: "AI Product Photography Generator for D2C Brands India",
  },
  description:
    "Turn mobile product photos into Amazon-ready hero shots and Instagram ad creatives in 60 seconds. AI product photography for skincare, perfume, watches, gadgets and food brands.",
  keywords: [
    // Core
    "AI product photoshoot",
    "AI product photography India",
    "AI product photography generator",
    "ecommerce product AI photography",
    "ecommerce hero image AI",
    "D2C product shoot AI",
    // Marketplace-specific
    "Amazon product photo AI",
    "Flipkart catalogue image AI",
    "Meesho product image AI",
    // Category-specific
    "AI skincare photography",
    "AI perfume product shoot",
    "AI watch photography",
    "AI sunglass product photo",
    "AI food product photography",
    "AI cosmetics catalogue",
  ],
  alternates: { canonical: `${SITE}/productography-ai` },
  openGraph: {
    title: "AI Product Photography Generator for D2C Brands India",
    description:
      "Mobile product photo to Amazon-ready hero shot in 60 seconds. AI product photography for Indian D2C and ecommerce brands.",
    url: `${SITE}/productography-ai`,
    siteName: "AgentForge AI",
    images: [{ url: "/banner1.png", width: 1200, height: 630, alt: "AI Product Photography Generator" }],
    locale: "en_IN",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "AI Product Photography Generator for D2C Brands India",
    description:
      "Amazon-ready product hero shots and Instagram ad creatives — generated by AI in 60 seconds.",
    images: ["/banner1.png"],
  },
};

// ============================================================
// JSON-LD: Service + AggregateRating + Reviews + Breadcrumb
// ============================================================
const serviceSchema = {
  "@context": "https://schema.org",
  "@type": "Service",
  name: "Productography AI",
  alternateName: "AI Product Photography Generator India",
  description:
    "AI service that turns mobile product photos into Amazon-ready hero shots and Instagram ad creatives in 60 seconds. Skincare, perfume, watches, gadgets and food brands.",
  provider: {
    "@type": "Organization",
    name: "AgentForge AI",
    url: SITE,
  },
  areaServed: { "@type": "Country", name: "India" },
  serviceType: "AI Product Photography Generation",
  url: `${SITE}/productography-ai`,
  image: `${SITE}/logo-new.jpg`,
  offers: {
    "@type": "Offer",
    priceCurrency: "INR",
    price: "1999",
    url: `${SITE}/pricing`,
    availability: "https://schema.org/InStock",
  },
  // NOTE: aggregateRating / review were removed on purpose. The values
  // were hardcoded, not taken from real customer reviews, which breaks
  // Google's review-snippet rules. Add them back only when they are
  // computed from approved testimonials in the database.
};

const breadcrumbSchema = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "Home", item: SITE },
    {
      "@type": "ListItem",
      position: 2,
      name: "Productography AI",
      item: `${SITE}/productography-ai`,
    },
  ],
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(serviceSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />
      {children}
    </>
  );
}
