-- ============================================================
-- 06 — Supabase advisor: policy and index warnings   (NOT applied yet)
-- ============================================================
-- Generated by scripts/staging/gen_policy_migration.py from the rules
-- as they are after migrations 00–05. Clears three performance
-- warnings of the Supabase advisor without changing who can see or
-- change what:
--
--   • "Auth RLS Initialization Plan" — auth.uid() / auth.jwt() /
--     auth.role() are written as (select auth.uid()) so Postgres
--     works them out once per query instead of once per row.
--   • "Multiple Permissive Policies" — on 44 tables several rules
--     applied to the same role and action. They are folded into one
--     rule per role and action; its condition is the OR of the old
--     conditions, which is exactly how Postgres combined them.
--     Rules that were written "to public" now name the two browser
--     roles (anon, authenticated) — the server role is not affected
--     by row-level security at all.
--   • "Duplicate Index" — two pairs of identical unique indexes.
--
-- 7 tables are changed in place (same rule names), 44 tables get
-- new rule names "<table>: <action>".
--
-- Checked on the local replica (scripts/staging/advisor-checks.sh):
-- every table, as a visitor, two customers, the founder and one team
-- member per permission, reads / inserts / updates / deletes sample
-- rows before and after — the results are identical; Supabase's own
-- advisor queries then report 0 for these three checks.
--
-- Run in ONE transaction (the Supabase SQL editor does that; it will
-- ask for confirmation because rules are replaced).
-- Rollback: sql/rollback/06-advisor-policies-and-indexes.rollback.sql
-- ============================================================

begin;

-- academy_tasks: 2 rules -> 4 (one per role and action)
drop policy "Academy tasks admin manage" on public."academy_tasks";
drop policy "Academy tasks admin read" on public."academy_tasks";
create policy "academy_tasks: select" on public."academy_tasks" as permissive for select to authenticated
  using (((has_permission('hr.manage'::text) OR has_permission('*'::text))) OR ((has_permission('hr.view'::text) OR has_permission('hr.manage'::text) OR has_permission('*'::text))));
create policy "academy_tasks: insert" on public."academy_tasks" as permissive for insert to authenticated
  with check ((has_permission('hr.manage'::text) OR has_permission('*'::text)));
create policy "academy_tasks: update" on public."academy_tasks" as permissive for update to authenticated
  using ((has_permission('hr.manage'::text) OR has_permission('*'::text)))
  with check ((has_permission('hr.manage'::text) OR has_permission('*'::text)));
create policy "academy_tasks: delete" on public."academy_tasks" as permissive for delete to authenticated
  using ((has_permission('hr.manage'::text) OR has_permission('*'::text)));

-- admin_notification_reads: same rules, auth.*() worked out once per query
alter policy "notification_reads own only" on public."admin_notification_reads"
  using (((reader_email IS NOT NULL) AND (lower(reader_email) = lower(COALESCE(( SELECT u.email
   FROM auth.users u
  WHERE (u.id = ( SELECT auth.uid()))), (''::character varying)::text)))))
  with check (((reader_email IS NOT NULL) AND (lower(reader_email) = lower(COALESCE(( SELECT u.email
   FROM auth.users u
  WHERE (u.id = ( SELECT auth.uid()))), (''::character varying)::text)))));

-- admin_roles: 2 rules -> 4 (one per role and action)
drop policy "admin_roles read by admins" on public."admin_roles";
drop policy "admin_roles write founder only" on public."admin_roles";
create policy "admin_roles: select" on public."admin_roles" as permissive for select to authenticated
  using ((is_admin()) OR (has_permission('team.edit_role'::text)));
create policy "admin_roles: insert" on public."admin_roles" as permissive for insert to authenticated
  with check (has_permission('team.edit_role'::text));
create policy "admin_roles: update" on public."admin_roles" as permissive for update to authenticated
  using (has_permission('team.edit_role'::text))
  with check (has_permission('team.edit_role'::text));
create policy "admin_roles: delete" on public."admin_roles" as permissive for delete to authenticated
  using (has_permission('team.edit_role'::text));

-- admin_training_progress: same rules, auth.*() worked out once per query
alter policy "training own insert" on public."admin_training_progress"
  with check ((lower(email) = lower(COALESCE((( SELECT auth.jwt()) ->> 'email'::text), ''::text))));
alter policy "training own select" on public."admin_training_progress"
  using ((lower(email) = lower(COALESCE((( SELECT auth.jwt()) ->> 'email'::text), ''::text))));
alter policy "training own update" on public."admin_training_progress"
  using ((lower(email) = lower(COALESCE((( SELECT auth.jwt()) ->> 'email'::text), ''::text))))
  with check ((lower(email) = lower(COALESCE((( SELECT auth.jwt()) ->> 'email'::text), ''::text))));

-- admin_users: 3 rules -> 4 (one per role and action)
drop policy "Admin users can read own row" on public."admin_users";
drop policy "admin_users admin read" on public."admin_users";
drop policy "admin_users write by team" on public."admin_users";
create policy "admin_users: select" on public."admin_users" as permissive for select to authenticated
  using (((lower(email) = lower((( SELECT auth.jwt()) ->> 'email'::text)))) OR (is_admin()) OR (has_permission('team.add'::text)));
create policy "admin_users: insert" on public."admin_users" as permissive for insert to authenticated
  with check (has_permission('team.add'::text));
create policy "admin_users: update" on public."admin_users" as permissive for update to authenticated
  using (has_permission('team.add'::text))
  with check (has_permission('team.add'::text));
create policy "admin_users: delete" on public."admin_users" as permissive for delete to authenticated
  using (has_permission('team.add'::text));

-- affiliate_payouts: 2 rules -> 4 (one per role and action)
drop policy "affpay read" on public."affiliate_payouts";
drop policy "affpay write" on public."affiliate_payouts";
create policy "affiliate_payouts: select" on public."affiliate_payouts" as permissive for select to authenticated
  using (((has_permission('affiliates.view'::text) OR has_permission('*'::text))) OR ((has_permission('affiliates.manage'::text) OR has_permission('*'::text))));
create policy "affiliate_payouts: insert" on public."affiliate_payouts" as permissive for insert to authenticated
  with check ((has_permission('affiliates.manage'::text) OR has_permission('*'::text)));
create policy "affiliate_payouts: update" on public."affiliate_payouts" as permissive for update to authenticated
  using ((has_permission('affiliates.manage'::text) OR has_permission('*'::text)))
  with check ((has_permission('affiliates.manage'::text) OR has_permission('*'::text)));
create policy "affiliate_payouts: delete" on public."affiliate_payouts" as permissive for delete to authenticated
  using ((has_permission('affiliates.manage'::text) OR has_permission('*'::text)));

-- affiliate_referrals: 2 rules -> 4 (one per role and action)
drop policy "affref read" on public."affiliate_referrals";
drop policy "affref write" on public."affiliate_referrals";
create policy "affiliate_referrals: select" on public."affiliate_referrals" as permissive for select to authenticated
  using (((has_permission('affiliates.view'::text) OR has_permission('*'::text))) OR ((has_permission('affiliates.manage'::text) OR has_permission('*'::text))));
create policy "affiliate_referrals: insert" on public."affiliate_referrals" as permissive for insert to authenticated
  with check ((has_permission('affiliates.manage'::text) OR has_permission('*'::text)));
create policy "affiliate_referrals: update" on public."affiliate_referrals" as permissive for update to authenticated
  using ((has_permission('affiliates.manage'::text) OR has_permission('*'::text)))
  with check ((has_permission('affiliates.manage'::text) OR has_permission('*'::text)));
create policy "affiliate_referrals: delete" on public."affiliate_referrals" as permissive for delete to authenticated
  using ((has_permission('affiliates.manage'::text) OR has_permission('*'::text)));

-- affiliates: 2 rules -> 4 (one per role and action)
drop policy "aff read" on public."affiliates";
drop policy "aff write" on public."affiliates";
create policy "affiliates: select" on public."affiliates" as permissive for select to authenticated
  using (((has_permission('affiliates.view'::text) OR has_permission('*'::text))) OR ((has_permission('affiliates.manage'::text) OR has_permission('*'::text))));
create policy "affiliates: insert" on public."affiliates" as permissive for insert to authenticated
  with check ((has_permission('affiliates.manage'::text) OR has_permission('*'::text)));
create policy "affiliates: update" on public."affiliates" as permissive for update to authenticated
  using ((has_permission('affiliates.manage'::text) OR has_permission('*'::text)))
  with check ((has_permission('affiliates.manage'::text) OR has_permission('*'::text)));
create policy "affiliates: delete" on public."affiliates" as permissive for delete to authenticated
  using ((has_permission('affiliates.manage'::text) OR has_permission('*'::text)));

-- agent_costs: 2 rules -> 4 (one per role and action)
drop policy "agent_costs read" on public."agent_costs";
drop policy "agent_costs write" on public."agent_costs";
create policy "agent_costs: select" on public."agent_costs" as permissive for select to authenticated
  using ((has_permission('ai_costs.view'::text)) OR (has_permission('ai_costs.edit'::text)));
create policy "agent_costs: insert" on public."agent_costs" as permissive for insert to authenticated
  with check (has_permission('ai_costs.edit'::text));
create policy "agent_costs: update" on public."agent_costs" as permissive for update to authenticated
  using (has_permission('ai_costs.edit'::text))
  with check (has_permission('ai_costs.edit'::text));
create policy "agent_costs: delete" on public."agent_costs" as permissive for delete to authenticated
  using (has_permission('ai_costs.edit'::text));

-- ai_cost_settings: 2 rules -> 4 (one per role and action)
drop policy "ai_cost_settings read" on public."ai_cost_settings";
drop policy "ai_cost_settings write" on public."ai_cost_settings";
create policy "ai_cost_settings: select" on public."ai_cost_settings" as permissive for select to authenticated
  using ((has_permission('ai_costs.view'::text)) OR (has_permission('ai_costs.edit'::text)));
create policy "ai_cost_settings: insert" on public."ai_cost_settings" as permissive for insert to authenticated
  with check (has_permission('ai_costs.edit'::text));
create policy "ai_cost_settings: update" on public."ai_cost_settings" as permissive for update to authenticated
  using (has_permission('ai_costs.edit'::text))
  with check (has_permission('ai_costs.edit'::text));
create policy "ai_cost_settings: delete" on public."ai_cost_settings" as permissive for delete to authenticated
  using (has_permission('ai_costs.edit'::text));

-- attendance_breaks: 2 rules -> 4 (one per role and action)
drop policy "breaks admin" on public."attendance_breaks";
drop policy "breaks own" on public."attendance_breaks";
create policy "attendance_breaks: select" on public."attendance_breaks" as permissive for select to authenticated
  using (((has_permission('team.view'::text) OR has_permission('*'::text))) OR ((lower(member_email) = lower((( SELECT auth.jwt()) ->> 'email'::text)))));
create policy "attendance_breaks: insert" on public."attendance_breaks" as permissive for insert to authenticated
  with check ((lower(member_email) = lower((( SELECT auth.jwt()) ->> 'email'::text))));
create policy "attendance_breaks: update" on public."attendance_breaks" as permissive for update to authenticated
  using ((lower(member_email) = lower((( SELECT auth.jwt()) ->> 'email'::text))))
  with check ((lower(member_email) = lower((( SELECT auth.jwt()) ->> 'email'::text))));
create policy "attendance_breaks: delete" on public."attendance_breaks" as permissive for delete to authenticated
  using ((lower(member_email) = lower((( SELECT auth.jwt()) ->> 'email'::text))));

-- attendance_logs: 2 rules -> 4 (one per role and action)
drop policy "attendance admin" on public."attendance_logs";
drop policy "attendance own" on public."attendance_logs";
create policy "attendance_logs: select" on public."attendance_logs" as permissive for select to authenticated
  using ((has_permission('team.view'::text)) OR ((lower(member_email) = lower((( SELECT auth.jwt()) ->> 'email'::text)))));
create policy "attendance_logs: insert" on public."attendance_logs" as permissive for insert to authenticated
  with check ((lower(member_email) = lower((( SELECT auth.jwt()) ->> 'email'::text))));
create policy "attendance_logs: update" on public."attendance_logs" as permissive for update to authenticated
  using ((lower(member_email) = lower((( SELECT auth.jwt()) ->> 'email'::text))))
  with check ((lower(member_email) = lower((( SELECT auth.jwt()) ->> 'email'::text))));
create policy "attendance_logs: delete" on public."attendance_logs" as permissive for delete to authenticated
  using ((lower(member_email) = lower((( SELECT auth.jwt()) ->> 'email'::text))));

-- automation_rules: 2 rules -> 4 (one per role and action)
drop policy "automation read" on public."automation_rules";
drop policy "automation write" on public."automation_rules";
create policy "automation_rules: select" on public."automation_rules" as permissive for select to authenticated
  using ((has_permission('settings.view'::text)) OR (has_permission('settings.manage'::text)));
create policy "automation_rules: insert" on public."automation_rules" as permissive for insert to authenticated
  with check (has_permission('settings.manage'::text));
create policy "automation_rules: update" on public."automation_rules" as permissive for update to authenticated
  using (has_permission('settings.manage'::text))
  with check (has_permission('settings.manage'::text));
create policy "automation_rules: delete" on public."automation_rules" as permissive for delete to authenticated
  using (has_permission('settings.manage'::text));

-- bulk_jobs: same rules, auth.*() worked out once per query
alter policy "bulk_jobs owner only" on public."bulk_jobs"
  using ((( SELECT auth.uid()) = user_id))
  with check ((( SELECT auth.uid()) = user_id));

-- caller_reports: 2 rules -> 4 (one per role and action)
drop policy "cr admin" on public."caller_reports";
drop policy "cr own" on public."caller_reports";
create policy "caller_reports: select" on public."caller_reports" as permissive for select to authenticated
  using (((has_permission('team.view'::text) OR has_permission('*'::text))) OR ((lower(caller_email) = lower((( SELECT auth.jwt()) ->> 'email'::text)))));
create policy "caller_reports: insert" on public."caller_reports" as permissive for insert to authenticated
  with check ((lower(caller_email) = lower((( SELECT auth.jwt()) ->> 'email'::text))));
create policy "caller_reports: update" on public."caller_reports" as permissive for update to authenticated
  using ((lower(caller_email) = lower((( SELECT auth.jwt()) ->> 'email'::text))))
  with check ((lower(caller_email) = lower((( SELECT auth.jwt()) ->> 'email'::text))));
create policy "caller_reports: delete" on public."caller_reports" as permissive for delete to authenticated
  using ((lower(caller_email) = lower((( SELECT auth.jwt()) ->> 'email'::text))));

-- candidates: 3 rules -> 5 (one per role and action)
drop policy "cand apply" on public."candidates";
drop policy "cand read" on public."candidates";
drop policy "cand write" on public."candidates";
create policy "candidates: select" on public."candidates" as permissive for select to authenticated
  using (((has_permission('hr.view'::text) OR has_permission('*'::text))) OR ((has_permission('hr.manage'::text) OR has_permission('*'::text))));
create policy "candidates: insert (visitors)" on public."candidates" as permissive for insert to anon
  with check (((name IS NOT NULL) AND (email IS NOT NULL)));
create policy "candidates: insert (signed-in)" on public."candidates" as permissive for insert to authenticated
  with check ((has_permission('hr.manage'::text) OR has_permission('*'::text)));
create policy "candidates: update" on public."candidates" as permissive for update to authenticated
  using ((has_permission('hr.manage'::text) OR has_permission('*'::text)))
  with check ((has_permission('hr.manage'::text) OR has_permission('*'::text)));
create policy "candidates: delete" on public."candidates" as permissive for delete to authenticated
  using ((has_permission('hr.manage'::text) OR has_permission('*'::text)));

-- commission_rules: 2 rules -> 4 (one per role and action)
drop policy "commission_rules read" on public."commission_rules";
drop policy "commission_rules write" on public."commission_rules";
create policy "commission_rules: select" on public."commission_rules" as permissive for select to authenticated
  using ((has_permission('incentives.view'::text)) OR (has_permission('incentives.manage'::text)));
create policy "commission_rules: insert" on public."commission_rules" as permissive for insert to authenticated
  with check (has_permission('incentives.manage'::text));
create policy "commission_rules: update" on public."commission_rules" as permissive for update to authenticated
  using (has_permission('incentives.manage'::text))
  with check (has_permission('incentives.manage'::text));
create policy "commission_rules: delete" on public."commission_rules" as permissive for delete to authenticated
  using (has_permission('incentives.manage'::text));

-- credit_transactions: 3 rules -> 1 (one per role and action)
drop policy "Users read own credit tx" on public."credit_transactions";
drop policy "credit_tx admin read" on public."credit_transactions";
drop policy "credit_tx own read" on public."credit_transactions";
create policy "credit_transactions: select" on public."credit_transactions" as permissive for select to authenticated
  using (((( SELECT auth.uid()) = user_id)) OR (is_admin()));

-- deals: 2 rules -> 4 (one per role and action)
drop policy "deals read" on public."deals";
drop policy "deals write" on public."deals";
create policy "deals: select" on public."deals" as permissive for select to authenticated
  using ((has_permission('leads.view'::text)) OR (has_permission('leads.add'::text)));
create policy "deals: insert" on public."deals" as permissive for insert to authenticated
  with check (has_permission('leads.add'::text));
create policy "deals: update" on public."deals" as permissive for update to authenticated
  using (has_permission('leads.add'::text))
  with check (has_permission('leads.add'::text));
create policy "deals: delete" on public."deals" as permissive for delete to authenticated
  using (has_permission('leads.add'::text));

-- email_templates: 2 rules -> 4 (one per role and action)
drop policy "email_templates read by admins" on public."email_templates";
drop policy "email_templates write by editors" on public."email_templates";
create policy "email_templates: select" on public."email_templates" as permissive for select to authenticated
  using ((has_permission('email.view'::text)) OR (has_permission('email.edit'::text)));
create policy "email_templates: insert" on public."email_templates" as permissive for insert to authenticated
  with check (has_permission('email.edit'::text));
create policy "email_templates: update" on public."email_templates" as permissive for update to authenticated
  using (has_permission('email.edit'::text))
  with check (has_permission('email.edit'::text));
create policy "email_templates: delete" on public."email_templates" as permissive for delete to authenticated
  using (has_permission('email.edit'::text));

-- error_logs: 2 rules -> 4 (one per role and action)
drop policy "errors read" on public."error_logs";
drop policy "errors write" on public."error_logs";
create policy "error_logs: select" on public."error_logs" as permissive for select to authenticated
  using (((has_permission('audit.view'::text) OR has_permission('*'::text))) OR (has_permission('*'::text)));
create policy "error_logs: insert" on public."error_logs" as permissive for insert to authenticated
  with check (has_permission('*'::text));
create policy "error_logs: update" on public."error_logs" as permissive for update to authenticated
  using (has_permission('*'::text))
  with check (has_permission('*'::text));
create policy "error_logs: delete" on public."error_logs" as permissive for delete to authenticated
  using (has_permission('*'::text));

-- feedback: same rules, auth.*() worked out once per query
alter policy "Users can insert own feedback" on public."feedback"
  with check ((( SELECT auth.uid()) = user_id));
alter policy "Users can read own feedback" on public."feedback"
  using ((( SELECT auth.uid()) = user_id));

-- finance_expenses: 2 rules -> 4 (one per role and action)
drop policy "finance_expenses read" on public."finance_expenses";
drop policy "finance_expenses write" on public."finance_expenses";
create policy "finance_expenses: select" on public."finance_expenses" as permissive for select to authenticated
  using ((has_permission('finance.view'::text)) OR (has_permission('finance.edit'::text)));
create policy "finance_expenses: insert" on public."finance_expenses" as permissive for insert to authenticated
  with check (has_permission('finance.edit'::text));
create policy "finance_expenses: update" on public."finance_expenses" as permissive for update to authenticated
  using (has_permission('finance.edit'::text))
  with check (has_permission('finance.edit'::text));
create policy "finance_expenses: delete" on public."finance_expenses" as permissive for delete to authenticated
  using (has_permission('finance.edit'::text));

-- founder_goals: 2 rules -> 4 (one per role and action)
drop policy "founder_goals read" on public."founder_goals";
drop policy "founder_goals write" on public."founder_goals";
create policy "founder_goals: select" on public."founder_goals" as permissive for select to authenticated
  using (((has_permission('*'::text) OR has_permission('dashboard.view'::text))) OR (has_permission('*'::text)));
create policy "founder_goals: insert" on public."founder_goals" as permissive for insert to authenticated
  with check (has_permission('*'::text));
create policy "founder_goals: update" on public."founder_goals" as permissive for update to authenticated
  using (has_permission('*'::text))
  with check (has_permission('*'::text));
create policy "founder_goals: delete" on public."founder_goals" as permissive for delete to authenticated
  using (has_permission('*'::text));

-- generations: 2 rules -> 1 (one per role and action)
drop policy "Users can view own generations" on public."generations";
drop policy "Users read own generations" on public."generations";
create policy "generations: select" on public."generations" as permissive for select to anon, authenticated
  using ((( SELECT auth.uid()) = user_id));
alter policy "generations insert: server only (was: users can insert own)" on public."generations"
  with check ((( SELECT auth.uid()) = user_id));
alter policy "generations insert: server only (was: users insert own)" on public."generations"
  with check ((( SELECT auth.uid()) = user_id));

-- hr_employees: 2 rules -> 4 (one per role and action)
drop policy "hr_employees read" on public."hr_employees";
drop policy "hr_employees write" on public."hr_employees";
create policy "hr_employees: select" on public."hr_employees" as permissive for select to authenticated
  using ((has_permission('hr.view'::text)) OR (has_permission('hr.manage'::text)));
create policy "hr_employees: insert" on public."hr_employees" as permissive for insert to authenticated
  with check (has_permission('hr.manage'::text));
create policy "hr_employees: update" on public."hr_employees" as permissive for update to authenticated
  using (has_permission('hr.manage'::text))
  with check (has_permission('hr.manage'::text));
create policy "hr_employees: delete" on public."hr_employees" as permissive for delete to authenticated
  using (has_permission('hr.manage'::text));

-- hr_leaves: 2 rules -> 4 (one per role and action)
drop policy "hr_leaves read" on public."hr_leaves";
drop policy "hr_leaves write" on public."hr_leaves";
create policy "hr_leaves: select" on public."hr_leaves" as permissive for select to authenticated
  using ((has_permission('hr.view'::text)) OR (has_permission('hr.manage'::text)));
create policy "hr_leaves: insert" on public."hr_leaves" as permissive for insert to authenticated
  with check (has_permission('hr.manage'::text));
create policy "hr_leaves: update" on public."hr_leaves" as permissive for update to authenticated
  using (has_permission('hr.manage'::text))
  with check (has_permission('hr.manage'::text));
create policy "hr_leaves: delete" on public."hr_leaves" as permissive for delete to authenticated
  using (has_permission('hr.manage'::text));

-- hr_salary_records: 2 rules -> 4 (one per role and action)
drop policy "hr_salary read" on public."hr_salary_records";
drop policy "hr_salary write" on public."hr_salary_records";
create policy "hr_salary_records: select" on public."hr_salary_records" as permissive for select to authenticated
  using ((has_permission('hr.view'::text)) OR (has_permission('hr.manage'::text)));
create policy "hr_salary_records: insert" on public."hr_salary_records" as permissive for insert to authenticated
  with check (has_permission('hr.manage'::text));
create policy "hr_salary_records: update" on public."hr_salary_records" as permissive for update to authenticated
  using (has_permission('hr.manage'::text))
  with check (has_permission('hr.manage'::text));
create policy "hr_salary_records: delete" on public."hr_salary_records" as permissive for delete to authenticated
  using (has_permission('hr.manage'::text));

-- invoices: 2 rules -> 4 (one per role and action)
drop policy "invoices admin all" on public."invoices";
drop policy "invoices own read" on public."invoices";
create policy "invoices: select" on public."invoices" as permissive for select to authenticated
  using ((is_admin()) OR ((( SELECT auth.uid()) = user_id)));
create policy "invoices: insert" on public."invoices" as permissive for insert to authenticated
  with check (is_admin());
create policy "invoices: update" on public."invoices" as permissive for update to authenticated
  using (is_admin())
  with check (is_admin());
create policy "invoices: delete" on public."invoices" as permissive for delete to authenticated
  using (is_admin());

-- kb_articles: 2 rules -> 4 (one per role and action)
drop policy "kb_articles read" on public."kb_articles";
drop policy "kb_articles write" on public."kb_articles";
create policy "kb_articles: select" on public."kb_articles" as permissive for select to authenticated
  using ((has_permission('kb.view'::text)) OR (has_permission('kb.manage'::text)));
create policy "kb_articles: insert" on public."kb_articles" as permissive for insert to authenticated
  with check (has_permission('kb.manage'::text));
create policy "kb_articles: update" on public."kb_articles" as permissive for update to authenticated
  using (has_permission('kb.manage'::text))
  with check (has_permission('kb.manage'::text));
create policy "kb_articles: delete" on public."kb_articles" as permissive for delete to authenticated
  using (has_permission('kb.manage'::text));

-- member_badges: 2 rules -> 4 (one per role and action)
drop policy "badges read" on public."member_badges";
drop policy "badges write" on public."member_badges";
create policy "member_badges: select" on public."member_badges" as permissive for select to authenticated
  using ((has_permission('team.view'::text)) OR (has_permission('incentives.manage'::text)));
create policy "member_badges: insert" on public."member_badges" as permissive for insert to authenticated
  with check (has_permission('incentives.manage'::text));
create policy "member_badges: update" on public."member_badges" as permissive for update to authenticated
  using (has_permission('incentives.manage'::text))
  with check (has_permission('incentives.manage'::text));
create policy "member_badges: delete" on public."member_badges" as permissive for delete to authenticated
  using (has_permission('incentives.manage'::text));

-- payments: 2 rules -> 1 (one per role and action)
drop policy "Users can view own payments" on public."payments";
drop policy "payments admin read" on public."payments";
create policy "payments: select" on public."payments" as permissive for select to authenticated
  using (((( SELECT auth.uid()) = user_id)) OR (is_admin()));

-- posts: 3 rules -> 5 (one per role and action)
drop policy "posts admin read all" on public."posts";
drop policy "posts admin write" on public."posts";
drop policy "posts public read published" on public."posts";
create policy "posts: select (visitors)" on public."posts" as permissive for select to anon
  using ((status = 'published'::text));
create policy "posts: select (signed-in)" on public."posts" as permissive for select to authenticated
  using ((is_admin()) OR ((status = 'published'::text)));
create policy "posts: insert" on public."posts" as permissive for insert to authenticated
  with check (is_admin());
create policy "posts: update" on public."posts" as permissive for update to authenticated
  using (is_admin())
  with check (is_admin());
create policy "posts: delete" on public."posts" as permissive for delete to authenticated
  using (is_admin());

-- profiles: 5 rules -> 3 (one per role and action)
drop policy "Users can insert own profile" on public."profiles";
drop policy "Users can read own profile" on public."profiles";
drop policy "Users can update own profile" on public."profiles";
drop policy "Users can view own profile" on public."profiles";
drop policy "profiles admin read" on public."profiles";
create policy "profiles: select" on public."profiles" as permissive for select to authenticated
  using (((id = ( SELECT auth.uid()))) OR ((( SELECT auth.uid()) = id)) OR (is_admin()));
create policy "profiles: insert" on public."profiles" as permissive for insert to authenticated
  with check ((id = ( SELECT auth.uid())));
create policy "profiles: update" on public."profiles" as permissive for update to authenticated
  using ((( SELECT auth.uid()) = id))
  with check ((( SELECT auth.uid()) = id));

-- recruitment_questions: 2 rules -> 4 (one per role and action)
drop policy "rq read" on public."recruitment_questions";
drop policy "rq write" on public."recruitment_questions";
create policy "recruitment_questions: select" on public."recruitment_questions" as permissive for select to authenticated
  using (((has_permission('hr.view'::text) OR has_permission('*'::text))) OR ((has_permission('hr.manage'::text) OR has_permission('*'::text))));
create policy "recruitment_questions: insert" on public."recruitment_questions" as permissive for insert to authenticated
  with check ((has_permission('hr.manage'::text) OR has_permission('*'::text)));
create policy "recruitment_questions: update" on public."recruitment_questions" as permissive for update to authenticated
  using ((has_permission('hr.manage'::text) OR has_permission('*'::text)))
  with check ((has_permission('hr.manage'::text) OR has_permission('*'::text)));
create policy "recruitment_questions: delete" on public."recruitment_questions" as permissive for delete to authenticated
  using ((has_permission('hr.manage'::text) OR has_permission('*'::text)));

-- recruitment_roles: 2 rules -> 4 (one per role and action)
drop policy "rec_roles read" on public."recruitment_roles";
drop policy "rec_roles write" on public."recruitment_roles";
create policy "recruitment_roles: select" on public."recruitment_roles" as permissive for select to anon, authenticated
  using (true);
create policy "recruitment_roles: insert" on public."recruitment_roles" as permissive for insert to authenticated
  with check ((has_permission('hr.manage'::text) OR has_permission('*'::text)));
create policy "recruitment_roles: update" on public."recruitment_roles" as permissive for update to authenticated
  using ((has_permission('hr.manage'::text) OR has_permission('*'::text)))
  with check ((has_permission('hr.manage'::text) OR has_permission('*'::text)));
create policy "recruitment_roles: delete" on public."recruitment_roles" as permissive for delete to authenticated
  using ((has_permission('hr.manage'::text) OR has_permission('*'::text)));

-- recruitment_training: 2 rules -> 4 (one per role and action)
drop policy "training read" on public."recruitment_training";
drop policy "training write" on public."recruitment_training";
create policy "recruitment_training: select" on public."recruitment_training" as permissive for select to anon, authenticated
  using (true);
create policy "recruitment_training: insert" on public."recruitment_training" as permissive for insert to authenticated
  with check ((has_permission('hr.manage'::text) OR has_permission('*'::text)));
create policy "recruitment_training: update" on public."recruitment_training" as permissive for update to authenticated
  using ((has_permission('hr.manage'::text) OR has_permission('*'::text)))
  with check ((has_permission('hr.manage'::text) OR has_permission('*'::text)));
create policy "recruitment_training: delete" on public."recruitment_training" as permissive for delete to authenticated
  using ((has_permission('hr.manage'::text) OR has_permission('*'::text)));

-- referral_earnings: 2 rules -> 4 (one per role and action)
drop policy "re_auth_write" on public."referral_earnings";
drop policy "re_team_read" on public."referral_earnings";
create policy "referral_earnings: select" on public."referral_earnings" as permissive for select to authenticated
  using (((has_permission('hr.manage'::text) OR has_permission('*'::text))) OR ((has_permission('finance.view'::text) OR has_permission('affiliates.view'::text) OR has_permission('marketing.view'::text) OR has_permission('hr.view'::text) OR has_permission('*'::text))));
create policy "referral_earnings: insert" on public."referral_earnings" as permissive for insert to authenticated
  with check ((has_permission('hr.manage'::text) OR has_permission('*'::text)));
create policy "referral_earnings: update" on public."referral_earnings" as permissive for update to authenticated
  using ((has_permission('hr.manage'::text) OR has_permission('*'::text)))
  with check ((has_permission('hr.manage'::text) OR has_permission('*'::text)));
create policy "referral_earnings: delete" on public."referral_earnings" as permissive for delete to authenticated
  using ((has_permission('hr.manage'::text) OR has_permission('*'::text)));

-- referrals: same rules, auth.*() worked out once per query
alter policy "referrals own read" on public."referrals"
  using (((( SELECT auth.uid()) = referrer_id) OR (( SELECT auth.uid()) = referred_id) OR is_admin()));

-- refund_requests: 2 rules -> 4 (one per role and action)
drop policy "refundreq read" on public."refund_requests";
drop policy "refundreq write" on public."refund_requests";
create policy "refund_requests: select" on public."refund_requests" as permissive for select to authenticated
  using (((has_permission('invoices.refund'::text) OR has_permission('support.view'::text) OR has_permission('*'::text))) OR ((has_permission('invoices.refund'::text) OR has_permission('support.manage'::text) OR has_permission('*'::text))));
create policy "refund_requests: insert" on public."refund_requests" as permissive for insert to authenticated
  with check ((has_permission('invoices.refund'::text) OR has_permission('support.manage'::text) OR has_permission('*'::text)));
create policy "refund_requests: update" on public."refund_requests" as permissive for update to authenticated
  using ((has_permission('invoices.refund'::text) OR has_permission('support.manage'::text) OR has_permission('*'::text)))
  with check ((has_permission('invoices.refund'::text) OR has_permission('support.manage'::text) OR has_permission('*'::text)));
create policy "refund_requests: delete" on public."refund_requests" as permissive for delete to authenticated
  using ((has_permission('invoices.refund'::text) OR has_permission('support.manage'::text) OR has_permission('*'::text)));

-- sales_resources: 2 rules -> 4 (one per role and action)
drop policy "resources read" on public."sales_resources";
drop policy "resources write" on public."sales_resources";
create policy "sales_resources: select" on public."sales_resources" as permissive for select to authenticated
  using (((has_permission('leads.view'::text) OR has_permission('kb.view'::text) OR has_permission('*'::text))) OR ((has_permission('hr.manage'::text) OR has_permission('*'::text))));
create policy "sales_resources: insert" on public."sales_resources" as permissive for insert to authenticated
  with check ((has_permission('hr.manage'::text) OR has_permission('*'::text)));
create policy "sales_resources: update" on public."sales_resources" as permissive for update to authenticated
  using ((has_permission('hr.manage'::text) OR has_permission('*'::text)))
  with check ((has_permission('hr.manage'::text) OR has_permission('*'::text)));
create policy "sales_resources: delete" on public."sales_resources" as permissive for delete to authenticated
  using ((has_permission('hr.manage'::text) OR has_permission('*'::text)));

-- sales_targets: 2 rules -> 4 (one per role and action)
drop policy "sales_targets read" on public."sales_targets";
drop policy "sales_targets write" on public."sales_targets";
create policy "sales_targets: select" on public."sales_targets" as permissive for select to authenticated
  using ((has_permission('incentives.view'::text)) OR (has_permission('incentives.manage'::text)));
create policy "sales_targets: insert" on public."sales_targets" as permissive for insert to authenticated
  with check (has_permission('incentives.manage'::text));
create policy "sales_targets: update" on public."sales_targets" as permissive for update to authenticated
  using (has_permission('incentives.manage'::text))
  with check (has_permission('incentives.manage'::text));
create policy "sales_targets: delete" on public."sales_targets" as permissive for delete to authenticated
  using (has_permission('incentives.manage'::text));

-- social_designs: same rules, auth.*() worked out once per query
alter policy "social_designs service role only" on public."social_designs"
  using ((( SELECT auth.role()) = 'service_role'::text))
  with check ((( SELECT auth.role()) = 'service_role'::text));

-- support_tickets: 2 rules -> 5 (one per role and action)
drop policy "support public submit" on public."support_tickets";
drop policy "support_tickets admin" on public."support_tickets";
create policy "support_tickets: select" on public."support_tickets" as permissive for select to authenticated
  using (has_permission('support.view'::text));
create policy "support_tickets: insert (visitors)" on public."support_tickets" as permissive for insert to anon
  with check ((status = 'open'::text));
create policy "support_tickets: insert (signed-in)" on public."support_tickets" as permissive for insert to authenticated
  with check (((status = 'open'::text)) OR (has_permission('support.manage'::text)));
create policy "support_tickets: update" on public."support_tickets" as permissive for update to authenticated
  using (has_permission('support.view'::text))
  with check (has_permission('support.manage'::text));
create policy "support_tickets: delete" on public."support_tickets" as permissive for delete to authenticated
  using (has_permission('support.view'::text));

-- system_settings: 2 rules -> 4 (one per role and action)
drop policy "system_settings read" on public."system_settings";
drop policy "system_settings write" on public."system_settings";
create policy "system_settings: select" on public."system_settings" as permissive for select to authenticated
  using ((has_permission('settings.view'::text)) OR (has_permission('settings.manage'::text)));
create policy "system_settings: insert" on public."system_settings" as permissive for insert to authenticated
  with check (has_permission('settings.manage'::text));
create policy "system_settings: update" on public."system_settings" as permissive for update to authenticated
  using (has_permission('settings.manage'::text))
  with check (has_permission('settings.manage'::text));
create policy "system_settings: delete" on public."system_settings" as permissive for delete to authenticated
  using (has_permission('settings.manage'::text));

-- testimonials: 6 rules -> 6 (one per role and action)
drop policy "authenticated_insert" on public."testimonials";
drop policy "public_read_approved" on public."testimonials";
drop policy "testimonials admin manage" on public."testimonials";
drop policy "testimonials admin read" on public."testimonials";
drop policy "testimonials public read approved" on public."testimonials";
drop policy "testimonials public submit" on public."testimonials";
create policy "testimonials: select (visitors)" on public."testimonials" as permissive for select to anon
  using ((status = 'approved'::text));
create policy "testimonials: select (signed-in)" on public."testimonials" as permissive for select to authenticated
  using (((status = 'approved'::text)) OR (is_admin()));
create policy "testimonials: insert (visitors)" on public."testimonials" as permissive for insert to anon
  with check ((((( SELECT auth.uid()) = user_id) OR (user_id IS NULL))) OR ((status = 'pending'::text)));
create policy "testimonials: insert (signed-in)" on public."testimonials" as permissive for insert to authenticated
  with check ((((( SELECT auth.uid()) = user_id) OR (user_id IS NULL))) OR (is_admin()) OR ((status = 'pending'::text)));
create policy "testimonials: update" on public."testimonials" as permissive for update to authenticated
  using (is_admin())
  with check (is_admin());
create policy "testimonials: delete" on public."testimonials" as permissive for delete to authenticated
  using (is_admin());

-- user_notifications: same rules, auth.*() worked out once per query
alter policy "Users read own notifications" on public."user_notifications"
  using ((user_id = ( SELECT auth.uid())));
alter policy "Users update own notifications" on public."user_notifications"
  using ((user_id = ( SELECT auth.uid())));

-- whatsapp_broadcasts: 2 rules -> 4 (one per role and action)
drop policy "wabc read" on public."whatsapp_broadcasts";
drop policy "wabc write" on public."whatsapp_broadcasts";
create policy "whatsapp_broadcasts: select" on public."whatsapp_broadcasts" as permissive for select to authenticated
  using (((has_permission('marketing.view'::text) OR has_permission('support.view'::text) OR has_permission('*'::text))) OR ((has_permission('support.manage'::text) OR has_permission('*'::text))));
create policy "whatsapp_broadcasts: insert" on public."whatsapp_broadcasts" as permissive for insert to authenticated
  with check ((has_permission('support.manage'::text) OR has_permission('*'::text)));
create policy "whatsapp_broadcasts: update" on public."whatsapp_broadcasts" as permissive for update to authenticated
  using ((has_permission('support.manage'::text) OR has_permission('*'::text)))
  with check ((has_permission('support.manage'::text) OR has_permission('*'::text)));
create policy "whatsapp_broadcasts: delete" on public."whatsapp_broadcasts" as permissive for delete to authenticated
  using ((has_permission('support.manage'::text) OR has_permission('*'::text)));

-- whatsapp_contacts: 2 rules -> 4 (one per role and action)
drop policy "wac read" on public."whatsapp_contacts";
drop policy "wac write" on public."whatsapp_contacts";
create policy "whatsapp_contacts: select" on public."whatsapp_contacts" as permissive for select to authenticated
  using (((has_permission('support.view'::text) OR has_permission('*'::text))) OR ((has_permission('support.manage'::text) OR has_permission('*'::text))));
create policy "whatsapp_contacts: insert" on public."whatsapp_contacts" as permissive for insert to authenticated
  with check ((has_permission('support.manage'::text) OR has_permission('*'::text)));
create policy "whatsapp_contacts: update" on public."whatsapp_contacts" as permissive for update to authenticated
  using ((has_permission('support.manage'::text) OR has_permission('*'::text)))
  with check ((has_permission('support.manage'::text) OR has_permission('*'::text)));
create policy "whatsapp_contacts: delete" on public."whatsapp_contacts" as permissive for delete to authenticated
  using ((has_permission('support.manage'::text) OR has_permission('*'::text)));

-- whatsapp_messages: 2 rules -> 4 (one per role and action)
drop policy "wa read" on public."whatsapp_messages";
drop policy "wa write" on public."whatsapp_messages";
create policy "whatsapp_messages: select" on public."whatsapp_messages" as permissive for select to authenticated
  using (((has_permission('support.view'::text) OR has_permission('*'::text))) OR ((has_permission('support.manage'::text) OR has_permission('*'::text))));
create policy "whatsapp_messages: insert" on public."whatsapp_messages" as permissive for insert to authenticated
  with check ((has_permission('support.manage'::text) OR has_permission('*'::text)));
create policy "whatsapp_messages: update" on public."whatsapp_messages" as permissive for update to authenticated
  using ((has_permission('support.manage'::text) OR has_permission('*'::text)))
  with check ((has_permission('support.manage'::text) OR has_permission('*'::text)));
create policy "whatsapp_messages: delete" on public."whatsapp_messages" as permissive for delete to authenticated
  using ((has_permission('support.manage'::text) OR has_permission('*'::text)));

-- workshop_reviews: 4 rules -> 6 (one per role and action)
drop policy "wreviews admin manage" on public."workshop_reviews";
drop policy "wreviews admin read" on public."workshop_reviews";
drop policy "wreviews public read approved" on public."workshop_reviews";
drop policy "wreviews public submit" on public."workshop_reviews";
create policy "workshop_reviews: select (visitors)" on public."workshop_reviews" as permissive for select to anon
  using ((status = 'approved'::text));
create policy "workshop_reviews: select (signed-in)" on public."workshop_reviews" as permissive for select to authenticated
  using ((is_admin()) OR ((status = 'approved'::text)));
create policy "workshop_reviews: insert (visitors)" on public."workshop_reviews" as permissive for insert to anon
  with check ((status = 'pending'::text));
create policy "workshop_reviews: insert (signed-in)" on public."workshop_reviews" as permissive for insert to authenticated
  with check ((is_admin()) OR ((status = 'pending'::text)));
create policy "workshop_reviews: update" on public."workshop_reviews" as permissive for update to authenticated
  using (is_admin())
  with check (is_admin());
create policy "workshop_reviews: delete" on public."workshop_reviews" as permissive for delete to authenticated
  using (is_admin());

-- ── Duplicate indexes ───────────────────────────────────────────
-- feedback: two identical unique indexes on (user_id, generation_id).
-- "feedback_user_generation_unique" is the older one and stays.
drop index if exists public.feedback_user_generation_uniq;

-- payments: two identical UNIQUE constraints on razorpay_payment_id.
-- "payments_razorpay_payment_id_key" stays (add_credits_for_payment's
-- ON CONFLICT (razorpay_payment_id) works with either).
alter table public.payments drop constraint if exists unique_razorpay_payment_id;

commit;
