const ts = require(require("node:path").resolve(__dirname, "../../node_modules/typescript"));
const fs = require("node:fs"), path = require("node:path"), Module = require("node:module");
const ROOT = require("node:path").resolve(__dirname, "../..");
function load(rel, stubs = {}) {
  const src = fs.readFileSync(path.join(ROOT, rel), "utf8");
  const js = ts.transpileModule(src, { compilerOptions: { module: "commonjs", target: "es2022" } }).outputText;
  const m = new Module(rel); m.paths = Module._nodeModulePaths(ROOT);
  const req = (id) => (id in stubs ? stubs[id] : id.startsWith("@/") ? load(id.slice(2) + ".ts", stubs) : require(require.resolve(id, { paths: [ROOT] })));
  new Function("exports", "require", "module", js)(m.exports, req, m); return m.exports;
}
const R = load("lib/generationRefund.ts", { "@/lib/creditsServer": {} });
const P = load("lib/razorpayPlans.ts");
let pass = 0, fail = 0; const t = (name, got, want) => { const ok = JSON.stringify(got) === JSON.stringify(want); ok ? pass++ : fail++; console.log(`${ok ? "PASS" : "FAIL"}  ${name}${ok ? "" : `  got ${JSON.stringify(got)} want ${JSON.stringify(want)}`}`); };
const L = (charged, refunded = 0, hasCharge = charged > 0) => ({ charged, refunded, hasCharge });
const d = (o) => R.duplicateChargeAmount({ isTeam: false, status: "completed", creditsUsed: 0, personal: L(0), teamCharged: false, personalBatch: null, ...o });
t("team gen, team paid, personal also charged 15 → 15 back", d({ isTeam: true, teamCharged: true, personal: L(15) }), 15);
t("team gen, personal charged then already refunded by n8n → 0", d({ isTeam: true, teamCharged: true, personal: L(15, 15) }), 0);
t("team gen, NO team charge on record → leave it (0)", d({ isTeam: true, teamCharged: false, personal: L(15) }), 0);
t("team gen (unlimited team plan, 0-credit charge row counts as paid) → 15 back", d({ isTeam: true, teamCharged: true, personal: L(17) }), 17);
t("team gen failed, personal charged → still returned", d({ isTeam: true, status: "failed", teamCharged: true, personal: L(15) }), 15);
t("personal, route charged 17, ledger shows 17 → 0", d({ creditsUsed: 17, personal: L(17) }), 0);
t("personal, route charged 17, n8n charged 15 more → 15 back", d({ creditsUsed: 17, personal: L(32) }), 15);
t("personal, route charged 30, n8n charged 30 more → 30 back", d({ creditsUsed: 30, personal: L(60) }), 30);
t("personal, duplicate already refunded → 0", d({ creditsUsed: 15, personal: L(30, 15) }), 0);
t("personal, n8n is the payer (credits_used 0) → never a duplicate", d({ creditsUsed: 0, personal: L(15) }), 0);
t("personal FAILED → handled by the failed-refund path, not here", d({ status: "failed", creditsUsed: 15, personal: L(30) }), 0);
t("bulk item: batch charge exists, item id also charged 15 → 15 back", d({ creditsUsed: 15, personal: L(15), personalBatch: L(45) }), 15);
t("bulk item: batch charge exists, nothing under item id → 0", d({ creditsUsed: 15, personal: L(0), personalBatch: L(45) }), 0);
t("absurd ledger (charged 500 extra) → capped at one image's price (45)", d({ creditsUsed: 15, personal: L(515) }), 45);
t("rating reward line is not counted as a refund", R.summariseLedger([{ delta: -15, reason: "textile_generate" }, { delta: 1, reason: "feedback_reward" }]), { charged: 15, refunded: 0, hasCharge: true });
t("duplicate refund line IS counted as a refund", R.summariseLedger([{ delta: -15, reason: "x" }, { delta: -15, reason: "x" }, { delta: 15, reason: "refund:duplicate_charge" }]), { charged: 30, refunded: 15, hasCharge: true });
const order = (notes, rupees) => ({ id: "order_1", amount: rupees * 100, currency: "INR", notes });
const pay = (rupees, extra = {}) => ({ id: "pay_1", order_id: "order_1", amount: rupees * 100, status: "captured", ...extra });
const fx = (o, p, e) => !!P.verifyFixedPriceOrder(o, p, e);
t("deposit: right type + ₹500 → ok", fx(order({ type: "security_deposit", candidate_id: "x" }, 500), pay(500), { type: "security_deposit", amountRupees: 500 }), true);
t("deposit: workshop order → no", fx(order({ type: "workshop" }, 99), pay(99), { type: "security_deposit", amountRupees: 500 }), false);
t("deposit: right type, ₹1 order → no", fx(order({ type: "security_deposit" }, 1), pay(1), { type: "security_deposit", amountRupees: 500 }), false);
t("deposit: payment of another order → no", fx(order({ type: "security_deposit" }, 500), pay(500, { order_id: "order_2" }), { type: "security_deposit", amountRupees: 500 }), false);
t("deposit: payment only 'created' → no", fx(order({ type: "security_deposit" }, 500), pay(500, { status: "created" }), { type: "security_deposit", amountRupees: 500 }), false);
t("deposit: USD order → no", fx({ ...order({ type: "security_deposit" }, 500), currency: "USD" }, pay(500), { type: "security_deposit", amountRupees: 500 }), false);
t("workshop: credit-plan order → no", fx(order({ type: "credit_plan", userId: "u", planName: "Starter" }, 1999), pay(1999), { type: "workshop", amountRupees: 99 }), false);
t("plan: payment.notes cannot stand in for order notes", P.verifyPlanOrder(order({}, 1999), pay(1999, { notes: { userId: "11111111-1111-4111-8111-111111111111", planName: "Starter" } })), null);
// ── one price table, one plan list ──────────────────────────
const C = load("lib/creditPricing.ts"), PC = load("lib/planCatalog.ts"), CR = load("lib/chargeRules.ts");
const img = (o) => C.perImageCredits({ ultra: false, mobile: false, ...o });
t("price: Premium square = 15", img({}), 15);
t("price: Premium mobile = 17", img({ mobile: true }), 17);
t("price: Ultra HD square = 30", img({ ultra: true }), 30);
t("price: Ultra HD mobile = 32", img({ ultra: true, mobile: true }), 32);
t("price: Ultra mobile + own scene + own model + 5 branding items = 41", img({ ultra: true, mobile: true, ownScene: true, ownModel: true, brandingItems: 5 }), 41);
t("price: a negative branding count is ignored", img({ brandingItems: -3 }), 15);
t("server range, Textile Ultra mobile + scene + model: 36 to 40 (4 branding items)", C.textileCreditRange({ quality: "Ultra HD", output_size: "1080x1920", reference_scene_url: "x", model_photo_url: "y" }), { floor: 36, ceiling: 40 });
t("server range, Jewellery Premium square: 15 to 20 (5 branding items)", C.jewelleryCreditRange({ shared_settings: { output_quality: "Premium", output_size: "Square 1080x1080" } }), { floor: 15, ceiling: 20 });
t("server range, Productography Ultra landscape: 32 to 37", C.productographyCreditRange({ quality: "ultra hd", output_size: "1920x1080" }), { floor: 32, ceiling: 37 });
t("browser says 1 credit → charged the floor", C.clampCredits(1, { floor: 15, ceiling: 20 }), 15);
t("browser says 999 credits → charged the ceiling", C.clampCredits(999, { floor: 15, ceiling: 20 }), 20);
t("the page's own number inside the range is kept", C.clampCredits(18, { floor: 15, ceiling: 20 }), 18);
t("price rows shown to customers come from the table", CR.PRICE_ROWS.map((r) => r.credits), ["15 credits", "30 credits", "+2 credits", "+2 credits", "+2 credits", "+1 credit each"]);
t("plan list: Starter 1,800 · Pro Creator 9,000 · Empire 36,000", Object.fromEntries(Object.entries(PC.PLAN_CONFIG).map(([k, v]) => [k, v.credits])), { Starter: 1800, "Pro Creator": 9000, Empire: 36000 });
t("payment routes read the same plan list", P.PLAN_CONFIG, PC.PLAN_CONFIG);
const facts = PC.planFactsLine();
t("AI reply prompts quote 9,000 and 36,000 credits, one-time, no unlimited", [/9,000 credits/.test(facts), /36,000 credits/.test(facts), /one-time/.test(facts), /12,000|50,000/.test(facts), /per month|\/month/.test(facts)], [true, true, true, false, false]);
t("charge rules: six rules, regeneration is never free", [CR.CHARGE_RULES.length, /normal price/.test(CR.REGENERATION_RULE_SHORT), /automatically/.test(CR.FAILED_RULE_SHORT)], [6, true, true]);
console.log(`\n${pass} passed, ${fail} failed`); process.exit(fail ? 1 : 0);
