import type { Metadata } from "next";

const SITE = "https://www.aiagentforge.in";

export const metadata: Metadata = {
  title: {
    absolute: "UGC Forge AI – Your Face, Your Product, AI Brand Shoot in Seconds",
  },
  description:
    "Upload a creator/model photo and your product. AgentForge UGC Forge generates premium UGC-style brand content while keeping the same face identity — pose, background and beauty style in seconds.",
  keywords: [
    "AI UGC generator India",
    "AI brand shoot",
    "UGC content AI",
    "AI influencer content generator",
    "AI model photoshoot same face",
    "product UGC AI India",
    "AI brand ambassador photos",
  ],
  alternates: { canonical: `${SITE}/ugc-forge` },
  openGraph: {
    title: "UGC Forge AI – Your Face, Your Product, AI Brand Shoot in Seconds",
    description:
      "Premium UGC-style brand content with your own face and product, generated by AI in seconds.",
    url: `${SITE}/ugc-forge`,
    siteName: "AgentForge AI",
    images: [{ url: "/banner1.png", width: 1200, height: 630, alt: "UGC Forge AI" }],
    locale: "en_IN",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "UGC Forge AI – Your Face, Your Product, AI Brand Shoot in Seconds",
    description: "AI UGC brand content with your face and product in seconds.",
    images: ["/banner1.png"],
  },
};

export default function UgcForgeLayout({ children }: { children: React.ReactNode }) {
  return children;
}
