import type { Metadata } from "next";

const SITE = "https://www.aiagentforge.in";

export const metadata: Metadata = {
  title: {
    absolute: "UGC Forge AI – Your Face, Your Product, AI Brand Shoot in Seconds",
  },
  description:
    "Upload a creator/model photo and your product. AgentForge UGC Forge generates premium UGC-style brand content while keeping the same face identity — pose, background and beauty style in seconds.",
  keywords: [
    "AI UGC generator India",
    "AI brand shoot",
    "UGC content AI",
    "AI influencer content generator",
    "AI model photoshoot same face",
    "product UGC AI India",
    "AI brand ambassador photos",
  ],
  alternates: { canonical: `${SITE}/ugc-forge` },
  openGraph: {
    title: "UGC Forge AI – Your Face, Your Product, AI Brand Shoot in Seconds",
    description:
      "Premium UGC-style brand content with your own face and product, generated by AI in seconds.",
    url: `${SITE}/ugc-forge`,
    siteName: "AgentForge AI",
    images: [{ url: "/banner1.png", width: 1200, height: 630, alt: "UGC Forge AI" }],
    locale: "en_IN",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "UGC Forge AI – Your Face, Your Product, AI Brand Shoot in Seconds",
    description: "AI UGC brand content with your face and product in seconds.",
    images: ["/banner1.png"],
  },
};

// ============================================================
// JSON-LD: Service + Breadcrumb
// ============================================================
const serviceSchema = {
  "@context": "https://schema.org",
  "@type": "Service",
  name: "UGC Forge AI",
  alternateName: "AI UGC Brand Shoot Generator India",
  description:
    "Upload a creator or model photo and your product. UGC Forge generates premium UGC-style brand content while keeping the same face identity — pose, background and beauty style preserved in seconds.",
  provider: {
    "@type": "Organization",
    name: "AgentForge AI",
    url: SITE,
  },
  areaServed: { "@type": "Country", name: "India" },
  serviceType: "AI UGC Content Generation",
  url: `${SITE}/ugc-forge`,
  image: `${SITE}/logo-new.jpg`,
  offers: {
    "@type": "Offer",
    priceCurrency: "INR",
    price: "1999",
    url: `${SITE}/pricing`,
    availability: "https://schema.org/InStock",
  },
  aggregateRating: {
    "@type": "AggregateRating",
    ratingValue: "4.9",
    ratingCount: "51",
    bestRating: "5",
    worstRating: "1",
  },
  review: [
    {
      "@type": "Review",
      author: { "@type": "Person", name: "Divya K." },
      reviewRating: { "@type": "Rating", ratingValue: "5", bestRating: "5" },
      reviewBody:
        "Used my own photo with the product — the brand shoot looks completely real. My Instagram engagement jumped after posting.",
      datePublished: "2026-05-24",
    },
    {
      "@type": "Review",
      author: { "@type": "Person", name: "Rahul T." },
      reviewRating: { "@type": "Rating", ratingValue: "5", bestRating: "5" },
      reviewBody:
        "No need to hire an influencer for a one-off collaboration. Generate the UGC content in seconds and ship to Meta Ads.",
      datePublished: "2026-05-21",
    },
  ],
};

const breadcrumbSchema = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "Home", item: SITE },
    { "@type": "ListItem", position: 2, name: "UGC Forge AI", item: `${SITE}/ugc-forge` },
  ],
};

export default function UgcForgeLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(serviceSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />
      {children}
    </>
  );
}
