"use client";

// /careers/test/[id] — Assessment: per-question timer, anti-cheat, PDF download on result.

import { useEffect, useRef, useState, useCallback } from "react";
import { useParams } from "next/navigation";
import { Download, Share2 } from "lucide-react";

type Q = { id: string; section: string; difficulty: string; question: string; options: string[]; time: number };
type Result = {
  total_score: number; section_scores: Record<string, number>;
  trust_score: number; passed: boolean; recommendation: string;
  candidate_name?: string; role_label?: string;
};

const MAX_WARNINGS = 3;

// ── PDF Generation (browser print) ──────────────────────────
function downloadScorePDF(result: Result, candidateId: string) {
  const date   = new Date().toLocaleDateString("en-IN", { day:"2-digit", month:"long", year:"numeric" });
  const scores = Object.entries(result.section_scores)
    .map(([sec, sc]) => `<tr><td style="padding:8px 12px;text-transform:capitalize;font-weight:600;">${sec}</td><td style="padding:8px 12px;text-align:right;font-weight:900;color:${sc>=60?"#10b981":"#f59e0b"};">${sc}%</td></tr>`)
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>AgentForge Assessment Scorecard</title>
  <style>
    * { margin:0; padding:0; box-sizing:border-box; }
    body { font-family: 'Arial', sans-serif; background:#fff8e8; color:#111827; padding:40px; }
    .card { background:#fff; border-radius:20px; padding:40px; box-shadow:0 4px 24px rgba(0,0,0,.08); max-width:600px; margin:0 auto; }
    .header { background:linear-gradient(135deg,#06b6d4,#3b82f6,#8b5cf6); border-radius:14px; padding:28px; text-align:center; color:#fff; margin-bottom:28px; }
    .header h1 { font-size:28px; font-weight:900; letter-spacing:-0.5px; }
    .header p  { font-size:13px; opacity:.85; margin-top:6px; }
    .badge { display:inline-block; padding:6px 16px; border-radius:999px; font-size:12px; font-weight:900; text-transform:uppercase; letter-spacing:.08em; }
    .pass { background:#d1fae5; color:#065f46; }
    .fail { background:#fef3c7; color:#92400e; }
    .score-big { font-size:72px; font-weight:900; text-align:center; background:linear-gradient(135deg,#06b6d4,#3b82f6); -webkit-background-clip:text; -webkit-text-fill-color:transparent; }
    .section-table { width:100%; border-collapse:collapse; margin-top:16px; }
    .section-table tr:nth-child(even) { background:#f9fafb; }
    .meta { font-size:11px; color:#6b7280; margin-top:24px; border-top:1px solid #e5e7eb; padding-top:16px; }
    @media print { body { padding:0; background:#fff; } .card { box-shadow:none; } }
  </style>
</head>
<body>
  <div class="card">
    <div class="header">
      <h1>AgentForge Assessment</h1>
      <p>Skill Test Scorecard</p>
    </div>
    <div style="text-align:center;margin-bottom:24px;">
      <span class="badge ${result.passed?"pass":"fail"}">${result.passed?"✅ Passed":"❌ Not Passed"}</span>
    </div>
    ${result.candidate_name ? `<p style="text-align:center;font-size:16px;font-weight:900;margin-bottom:4px;">${result.candidate_name}</p>` : ""}
    ${result.role_label ? `<p style="text-align:center;font-size:12px;color:#6b7280;margin-bottom:20px;">${result.role_label}</p>` : ""}
    <div class="score-big">${result.total_score}%</div>
    <p style="text-align:center;font-size:13px;color:#6b7280;margin-top:4px;">Overall Score · Pass = 60%</p>
    <table class="section-table">${scores}</table>
    <div class="meta">
      <p>Trust Score: ${result.trust_score}%</p>
      <p style="margin-top:4px;">Date: ${date}</p>
      <p style="margin-top:4px;">Candidate ID: ${candidateId}</p>
      <p style="margin-top:12px;font-size:10px;">This scorecard is auto-generated by AgentForge recruitment system. agentforge.in</p>
    </div>
  </div>
</body>
</html>`;

  const blob = new Blob([html], { type: "text/html" });
  const url  = URL.createObjectURL(blob);
  const w    = window.open(url, "_blank");
  if (w) {
    setTimeout(() => { w.print(); setTimeout(() => URL.revokeObjectURL(url), 3000); }, 600);
  }
}

export default function TestPage() {
  const { id } = useParams<{ id: string }>();

  const [phase, setPhase]     = useState<"intro"|"loading"|"test"|"result"|"error"|"received"|"cc_proposal">("intro");
  const [questions, setQuestions] = useState<Q[]>([]);
  const [idx, setIdx]         = useState(0);
  const [answers, setAnswers] = useState<Record<string, number>>({});
  const [timeLeft, setTimeLeft] = useState(0);
  const [warnings, setWarnings] = useState(0);
  const [error, setError]     = useState<string | null>(null);
  const [result, setResult]   = useState<Result | null>(null);
  const [ccData, setCcData]   = useState<{ ai_score: number; ai_verdict: string; referral_code?: string } | null>(null);
  const [ccResponse, setCcResponse] = useState<"yes"|"no"|null>(null);
  const [ccSubmitting, setCcSubmitting] = useState(false);

  const startedAt   = useRef<number>(0);
  const answersRef  = useRef(answers);
  const warnRef     = useRef(0);
  const submittedRef = useRef(false);
  answersRef.current = answers;

  // ── Start test ──
  async function start() {
    setPhase("loading");
    const res  = await fetch("/api/careers/questions", {
      method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ candidate_id: id }),
    });
    const json = await res.json();
    if (!json.ok) {
      if ((json.error ?? "").toLowerCase().includes("no questions")) {
        // Could be content-creator — fetch CC data
        const ccRes = await fetch(`/api/careers/content-creator?candidate_id=${id}`);
        const ccJson = await ccRes.json();
        if (ccJson.ok) { setCcData(ccJson); setPhase("cc_proposal"); }
        else { setPhase("received"); }
        return;
      }
      setError(json.error ?? "Could not load test."); setPhase("error"); return;
    }
    setQuestions(json.questions);
    setIdx(0);
    setTimeLeft(json.questions[0]?.time ?? 45);
    startedAt.current = Date.now();
    setPhase("test");
  }

  // ── Submit test ──
  const submit = useCallback(async (flags: number) => {
    if (submittedRef.current) return;
    submittedRef.current = true;
    const durationSecs = Math.round((Date.now() - startedAt.current) / 1000);
    setPhase("loading");
    const res  = await fetch("/api/careers/submit", {
      method: "POST", headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ candidate_id: id, answers: answersRef.current, cheat_flags: flags, duration_secs: durationSecs }),
    });
    const json = await res.json();
    if (!json.ok) { setError(json.error ?? "Submit failed."); setPhase("error"); return; }
    setResult(json); setPhase("result");
  }, [id]);

  // ── Next question ──
  const next = useCallback(() => {
    setIdx((cur) => {
      const nx = cur + 1;
      if (nx >= questions.length) { submit(warnRef.current); return cur; }
      setTimeLeft(questions[nx].time);
      return nx;
    });
  }, [questions, submit]);

  // ── Per-question timer ──
  useEffect(() => {
    if (phase !== "test") return;
    if (timeLeft <= 0) { next(); return; }
    const t = setTimeout(() => setTimeLeft((s) => s - 1), 1000);
    return () => clearTimeout(t);
  }, [phase, timeLeft, next]);

  // ── Anti-cheat ──
  useEffect(() => {
    if (phase !== "test") return;
    function onVis() {
      if (document.visibilityState === "hidden") {
        warnRef.current += 1; setWarnings(warnRef.current);
        if (warnRef.current >= MAX_WARNINGS + 1) submit(warnRef.current);
      }
    }
    function block(e: Event) { e.preventDefault(); warnRef.current += 1; setWarnings(warnRef.current); }
    document.addEventListener("visibilitychange", onVis);
    document.addEventListener("copy", block);
    document.addEventListener("paste", block);
    document.addEventListener("contextmenu", block);
    return () => {
      document.removeEventListener("visibilitychange", onVis);
      document.removeEventListener("copy", block);
      document.removeEventListener("paste", block);
      document.removeEventListener("contextmenu", block);
    };
  }, [phase, submit]);

  function choose(qid: string, oi: number) { setAnswers((p) => ({ ...p, [qid]: oi })); }

  async function handleCCResponse(resp: "yes" | "no") {
    setCcResponse(resp); setCcSubmitting(true);
    await fetch("/api/careers/content-creator/respond", {
      method: "POST", headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ candidate_id: id, response: resp }),
    }).catch(() => {});
    setCcSubmitting(false);
  }

  // ── RENDER ──
  if (phase === "intro") {
    return (
      <Shell>
        <p className="text-[11px] font-black uppercase tracking-[0.28em] text-cyan-600">Step 3 · Assessment</p>
        <h1 className="mt-2 text-2xl font-black">
          Skill <span className="bg-gradient-to-r from-cyan-500 to-blue-600 bg-clip-text text-transparent">Test</span>
        </h1>
        <ul className="mt-4 space-y-2 text-sm font-medium text-black/65 dark:text-white/65">
          <li>⏱️ Har question ka apna timer hai — jaldi jawab do.</li>
          <li>🚫 Tab switch ya copy-paste mat karo — {MAX_WARNINGS} warnings ke baad auto-submit.</li>
          <li>🔁 Maximum 3 attempts total milte hain.</li>
          <li>✅ Sahi jawab de — honest answers = best result. Best of luck!</li>
        </ul>
        <button onClick={start}
          className="mt-6 w-full rounded-full bg-gradient-to-r from-cyan-400 to-blue-600 py-3.5 text-sm font-black text-white shadow-xl shadow-cyan-500/30 transition hover:scale-[1.02] active:scale-95">
          Test Shuru Karo →
        </button>
      </Shell>
    );
  }

  if (phase === "loading") return <Shell><p className="py-10 text-center text-sm text-slate-500">Please wait…</p></Shell>;

  if (phase === "received") {
    return (
      <Shell>
        <div className="py-6 text-center">
          <p className="text-5xl">✅</p>
          <h1 className="mt-3 text-2xl font-black">Application <span className="bg-gradient-to-r from-cyan-500 to-blue-600 bg-clip-text text-transparent">Received!</span></h1>
          <p className="mt-2 text-sm font-medium text-black/60 dark:text-white/60">
            Thank you for applying to AgentForge. Hamari team aapki application review karke jald hi aapse contact karegi.
          </p>
          <p className="mt-4 text-[11px] font-bold text-black/40 dark:text-white/40">Aap ye window band kar sakte hain.</p>
        </div>
      </Shell>
    );
  }

  // Content Creator Referral Proposal
  if (phase === "cc_proposal" && ccData) {
    const isStrong = ccData.ai_score >= 50;
    return (
      <Shell>
        <div className="text-center">
          <p className="text-5xl">{isStrong ? "🌟" : "📊"}</p>
          <h1 className="mt-3 text-2xl font-black">Profile <span className="bg-gradient-to-r from-purple-500 to-pink-500 bg-clip-text text-transparent">Analysed!</span></h1>
          <p className="mt-1 text-sm text-black/55 dark:text-white/55">AI Score: <b>{ccData.ai_score}/100</b></p>
        </div>
        {isStrong ? (
          <>
            <div className="mt-5 rounded-2xl border border-purple-200/60 bg-purple-50/60 p-4 dark:border-purple-400/20 dark:bg-purple-500/5">
              <p className="text-sm font-black text-purple-800 dark:text-purple-200">🎉 We want to collaborate with you!</p>
              <p className="mt-2 text-sm font-medium leading-relaxed text-black/70 dark:text-white/70">
                Aapki social media reach kaafi acchi hai. Hum referral-based collaboration dhundh rahe hain.
              </p>
              <ul className="mt-3 space-y-1.5 text-sm font-medium text-black/65 dark:text-white/65">
                <li>🔗 Aapko ek unique referral link milega</li>
                <li>💰 Har purchase pe <b>10% commission</b></li>
                <li>📊 Real-time earning tracking portal</li>
                <li>🤝 Monthly collaboration review</li>
              </ul>
              <p className="mt-3 font-bold text-purple-700 dark:text-purple-300">Are you interested?</p>
            </div>
            {ccResponse === null ? (
              <div className="mt-4 grid grid-cols-2 gap-3">
                <button onClick={() => handleCCResponse("yes")} disabled={ccSubmitting}
                  className="rounded-full bg-gradient-to-r from-emerald-400 to-emerald-600 py-3 text-sm font-black text-white shadow-lg transition hover:scale-[1.02] disabled:opacity-50">
                  ✅ Yes, Interested!
                </button>
                <button onClick={() => handleCCResponse("no")} disabled={ccSubmitting}
                  className="rounded-full border border-black/10 bg-white py-3 text-sm font-black transition hover:scale-[1.02] dark:border-white/15 dark:bg-white/10 dark:text-white disabled:opacity-50">
                  Not Right Now
                </button>
              </div>
            ) : (
              <div className="mt-4 rounded-2xl border border-cyan-200/40 bg-white/85 p-5 text-center dark:border-cyan-400/20 dark:bg-white/[0.05]">
                <p className="text-3xl">{ccResponse === "yes" ? "🎉" : "👍"}</p>
                <p className="mt-2 text-sm font-black">{ccResponse === "yes" ? "Bahut accha! Hamar team aapko jald contact karegi." : "No problem! Hamari team aapko inform karegi."}</p>
                <p className="mt-1 text-[11px] font-bold text-black/40 dark:text-white/40">Our Team Will Contact You Soon.</p>
              </div>
            )}
          </>
        ) : (
          <div className="mt-5 rounded-2xl border border-amber-200/60 bg-amber-50/60 p-4 dark:border-amber-400/20 dark:bg-amber-500/5 text-center">
            <p className="text-sm font-medium text-black/70 dark:text-white/70">
              Shukriya apply karne ke liye! Hamar social media team aapki profile review karke jald hi aapse contact karegi.
            </p>
            <p className="mt-3 text-[11px] font-bold text-black/40 dark:text-white/40">Our Team Will Contact You Soon.</p>
          </div>
        )}
      </Shell>
    );
  }

  if (phase === "error") {
    return <Shell><div className="py-8 text-center"><p className="text-3xl">😕</p><p className="mt-3 text-sm font-medium text-rose-600">{error}</p></div></Shell>;
  }

  // ── Result Screen ──
  if (phase === "result" && result) {
    return (
      <Shell>
        <div className="text-center">
          <p className="text-5xl">{result.passed ? "🎉" : "💪"}</p>
          <h1 className="mt-3 text-2xl font-black text-slate-900 dark:text-white">
            {result.passed ? "You Passed!" : "Keep Going!"}
          </h1>
          <p className="mt-1 text-sm text-slate-500">
            {result.passed
              ? "Badhai ho! Hamari HR team jald hi aapko contact karegi."
              : `Dobaara try karo — training padh ke aao.`}
          </p>
          <div className="mt-6 inline-flex items-baseline gap-1">
            <span className="bg-gradient-to-r from-cyan-500 to-blue-600 bg-clip-text text-6xl font-black text-transparent">{result.total_score}</span>
            <span className="text-xl text-black/40 dark:text-white/40">%</span>
          </div>

          {/* PDF Download */}
          <div className="mt-4 flex flex-wrap items-center justify-center gap-2">
            <button onClick={() => downloadScorePDF(result, id)}
              className="inline-flex items-center gap-2 rounded-full border border-cyan-300/60 bg-white/80 px-5 py-2.5 text-sm font-black text-cyan-700 shadow transition hover:scale-[1.02] dark:border-cyan-400/30 dark:bg-white/[0.07] dark:text-cyan-300">
              <Download className="h-4 w-4" /> Download Score Card (PDF)
            </button>
          </div>
        </div>

        <div className="mt-6 space-y-2">
          {Object.entries(result.section_scores).map(([sec, sc]) => (
            <div key={sec}>
              <div className="flex justify-between text-xs">
                <span className="capitalize font-medium text-slate-700 dark:text-slate-300">{sec}</span>
                <span className="font-bold">{sc}%</span>
              </div>
              <div className="mt-1 h-2 w-full overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800">
                <div className={`h-full rounded-full ${sc >= 60 ? "bg-emerald-500" : "bg-amber-500"}`} style={{ width: `${sc}%` }} />
              </div>
            </div>
          ))}
        </div>

        {result.passed ? (
          <div className="mt-5 rounded-2xl border border-emerald-200/60 bg-emerald-50/60 p-4 text-center dark:border-emerald-400/20 dark:bg-emerald-500/5">
            <p className="text-sm font-black text-emerald-800 dark:text-emerald-200">🎊 Our Team Will Connect You Soon!</p>
            <p className="mt-1 text-[11px] font-medium text-black/60 dark:text-white/50">
              Hamari HR team aapko WhatsApp ya call pe contact karegi. Process samjhayegi aur salary confirm karegi.
            </p>
          </div>
        ) : (
          <div className="mt-5 rounded-2xl border border-amber-200/60 bg-amber-50/60 p-4 text-center dark:border-amber-400/20 dark:bg-amber-500/5">
            <p className="text-sm font-black text-amber-800 dark:text-amber-200">Aap dobara try kar sakte ho</p>
            <p className="mt-1 text-[11px] font-medium text-black/60 dark:text-white/50">
              3 attempts total milte hain. Training padh ke dobara aao — aasaan lagega.
            </p>
            <a href={`/careers/learn?role=telecaller&cid=${id}`}
              className="mt-3 inline-flex items-center gap-1.5 rounded-full bg-amber-500 px-5 py-2 text-xs font-black text-white shadow transition hover:scale-[1.02]">
              Training Dobara Padho →
            </a>
          </div>
        )}

        <p className="mt-5 text-center text-[11px] text-slate-400">Trust score: {result.trust_score}% · ID: {id.slice(0,8)}</p>
      </Shell>
    );
  }

  // ── Test in progress ──
  const q = questions[idx];
  if (!q) return <Shell><p className="py-10 text-center text-sm text-slate-500">…</p></Shell>;
  const danger = timeLeft <= 5;

  return (
    <Shell wide>
      <div className="flex items-center justify-between">
        <span className="text-xs font-black text-black/50 dark:text-white/50">Question {idx + 1} / {questions.length}</span>
        <div className="flex items-center gap-3">
          {warnings > 0 && (
            <span className="rounded-full bg-rose-100 px-2 py-0.5 text-[11px] font-bold text-rose-700 dark:bg-rose-500/10 dark:text-rose-300">
              ⚠️ {warnings}/{MAX_WARNINGS} warnings
            </span>
          )}
          <span className={`flex h-10 w-10 items-center justify-center rounded-full text-sm font-black tabular-nums shadow-md ${danger ? "bg-rose-500 text-white" : "bg-gradient-to-br from-cyan-400 to-blue-600 text-white"}`}>
            {timeLeft}
          </span>
        </div>
      </div>
      <div className="mt-2 h-1.5 w-full overflow-hidden rounded-full bg-black/5 dark:bg-white/10">
        <div className="h-full bg-gradient-to-r from-cyan-400 to-blue-600 transition-all" style={{ width: `${(idx / questions.length) * 100}%` }} />
      </div>
      <div className="mt-6">
        <span className="rounded-full bg-cyan-100 px-2.5 py-0.5 text-[10px] font-black uppercase capitalize tracking-wider text-cyan-700 dark:bg-cyan-500/10 dark:text-cyan-300">{q.section}</span>
        <p className="mt-3 select-none text-base font-black text-slate-900 dark:text-white sm:text-lg">{q.question}</p>
        <div className="mt-4 space-y-2">
          {q.options.map((o, oi) => {
            const sel = answers[q.id] === oi;
            return (
              <button key={oi} type="button" onClick={() => choose(q.id, oi)}
                className={`flex w-full items-center gap-3 rounded-xl border px-4 py-3 text-left text-sm transition ${sel ? "border-cyan-400 bg-cyan-50 shadow-sm dark:bg-cyan-500/10" : "border-cyan-200/40 hover:border-cyan-300 dark:border-white/10 dark:hover:border-white/20"}`}>
                <span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-xs font-black ${sel ? "bg-gradient-to-br from-cyan-400 to-blue-600 text-white" : "border border-cyan-300/60 text-black/40 dark:border-white/20 dark:text-white/40"}`}>{String.fromCharCode(65 + oi)}</span>
                <span className="select-none font-medium text-slate-800 dark:text-slate-100">{o}</span>
              </button>
            );
          })}
        </div>
      </div>
      <button onClick={next}
        className="mt-6 w-full rounded-full bg-gradient-to-r from-cyan-400 to-blue-600 py-3.5 text-sm font-black text-white shadow-xl shadow-cyan-500/30 transition hover:scale-[1.02] active:scale-95">
        {idx + 1 >= questions.length ? "Finish Test & See Score" : "Next Question →"}
      </button>
    </Shell>
  );
}

function Shell({ children, wide }: { children: React.ReactNode; wide?: boolean }) {
  return (
    <main className="relative min-h-screen bg-[#fff8e8] text-[#111827] dark:bg-[#070b14] dark:text-white">
      <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_top_left,#22d3ee44,transparent_35%),radial-gradient(circle_at_top_right,#8b5cf633,transparent_35%)]" />
      <div className={`relative z-10 mx-auto px-5 py-12 ${wide ? "max-w-2xl" : "max-w-md"}`}>
        <div className="rounded-3xl border border-cyan-200/40 bg-white/85 p-6 shadow-xl shadow-cyan-200/20 backdrop-blur dark:border-cyan-400/20 dark:bg-white/[0.05]">
          {children}
        </div>
      </div>
    </main>
  );
}
