import type { Metadata } from "next";

const SITE = "https://www.aiagentforge.in";

export const metadata: Metadata = {
  title: {
    absolute: "AI Jewellery Photoshoot Generator for Indian Jewellery Brands",
  },
  description:
    "AI jewellery photoshoots in 30 seconds — bridal sets, diamond rings, necklaces, earrings, kundan and pearls. Editorial-grade catalogue images built for Indian jewellery brands.",
  keywords: [
    // Core
    "AI jewellery photoshoot",
    "AI jewellery photoshoot generator",
    "AI jewellery photoshoot India",
    "jewellery product photography AI",
    "jewellery model generator",
    "AI jewellery catalogue",
    "jewellery model AI",
    "AI bridal jewellery catalogue",
    // Product-specific
    "AI diamond ring photo",
    "AI necklace catalogue",
    "AI earring photoshoot",
    "kundan jewellery AI India",
    "AI pearl jewellery photography",
    "AI gold jewellery catalogue",
  ],
  alternates: { canonical: `${SITE}/jewellery-ai` },
  openGraph: {
    title: "AI Jewellery Photoshoot Generator for Indian Jewellery Brands",
    description:
      "Generate bridal, diamond and daily-wear jewellery photoshoots with AI — editorial-grade catalogue images in 30 seconds. Built for Indian jewellery brands.",
    url: `${SITE}/jewellery-ai`,
    siteName: "AgentForge AI",
    images: [{ url: "/logo-new.jpg", width: 1200, height: 630, alt: "AI Jewellery Photoshoot Generator" }],
    locale: "en_IN",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "AI Jewellery Photoshoot Generator for Indian Jewellery Brands",
    description:
      "Bridal, diamond, kundan, pearls — editorial-grade jewellery photoshoots generated by AI in 30 seconds.",
    images: ["/logo-new.jpg"],
  },
};

// ============================================================
// JSON-LD: Service + AggregateRating + Reviews + Breadcrumb
// ============================================================
const serviceSchema = {
  "@context": "https://schema.org",
  "@type": "Service",
  name: "Jewellery AI Studio",
  alternateName: "AI Jewellery Photoshoot Generator",
  description:
    "AI service for jewellery photoshoots — bridal sets, diamond rings, necklaces, earrings, kundan and pearls. Editorial-grade catalogue images in 30 seconds.",
  provider: {
    "@type": "Organization",
    name: "AgentForge AI",
    url: SITE,
  },
  areaServed: { "@type": "Country", name: "India" },
  serviceType: "AI Jewellery Photoshoot Generation",
  url: `${SITE}/jewellery-ai`,
  image: `${SITE}/logo-new.jpg`,
  offers: {
    "@type": "Offer",
    priceCurrency: "INR",
    price: "1999",
    url: `${SITE}/pricing`,
    availability: "https://schema.org/InStock",
  },
  aggregateRating: {
    "@type": "AggregateRating",
    ratingValue: "4.9",
    ratingCount: "143",
    bestRating: "5",
    worstRating: "1",
  },
  review: [
    {
      "@type": "Review",
      author: { "@type": "Person", name: "Neha A." },
      reviewRating: { "@type": "Rating", ratingValue: "5", bestRating: "5" },
      reviewBody:
        "Necklace shots look exactly like DSLR work. Didn't even need to hire a model. Festive collection ready in 2 hours!",
      datePublished: "2026-05-22",
    },
    {
      "@type": "Review",
      author: { "@type": "Person", name: "Rohan G." },
      reviewRating: { "@type": "Rating", ratingValue: "5", bestRating: "5" },
      reviewBody:
        "Diamond ring reflections look stunning. Perfect for the catalogue — covered all designs in a single day.",
      datePublished: "2026-05-20",
    },
    {
      "@type": "Review",
      author: { "@type": "Person", name: "Priyanka M." },
      reviewRating: { "@type": "Rating", ratingValue: "5", bestRating: "5" },
      reviewBody:
        "Bridal jewellery model shoots used to be very expensive. Now I get the same look with AgentForge at a fraction of the cost.",
      datePublished: "2026-05-17",
    },
  ],
};

const breadcrumbSchema = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "Home", item: SITE },
    {
      "@type": "ListItem",
      position: 2,
      name: "Jewellery AI Studio",
      item: `${SITE}/jewellery-ai`,
    },
  ],
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(serviceSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />
      {children}
    </>
  );
}
