import type { Metadata } from "next";

const SITE = "https://www.aiagentforge.in";

export const metadata: Metadata = {
  title: {
    absolute: "AI Jewellery Photoshoot Generator for Indian Jewellery Brands",
  },
  description:
    "AI jewellery photoshoots in 60 seconds — bridal sets, diamond rings, necklaces, earrings, kundan and pearls. Editorial-grade catalogue images built for Indian jewellery brands.",
  keywords: [
    // Core
    "AI jewellery photoshoot",
    "AI jewellery photoshoot generator",
    "AI jewellery photoshoot India",
    "jewellery product photography AI",
    "jewellery model generator",
    "AI jewellery catalogue",
    "jewellery model AI",
    "AI bridal jewellery catalogue",
    // Product-specific
    "AI diamond ring photo",
    "AI necklace catalogue",
    "AI earring photoshoot",
    "kundan jewellery AI India",
    "AI pearl jewellery photography",
    "AI gold jewellery catalogue",
  ],
  alternates: { canonical: `${SITE}/jewellery-ai` },
  openGraph: {
    title: "AI Jewellery Photoshoot Generator for Indian Jewellery Brands",
    description:
      "Generate bridal, diamond and daily-wear jewellery photoshoots with AI — editorial-grade catalogue images in 60 seconds. Built for Indian jewellery brands.",
    url: `${SITE}/jewellery-ai`,
    siteName: "AgentForge AI",
    images: [{ url: "/banner1.png", width: 1200, height: 630, alt: "AI Jewellery Photoshoot Generator" }],
    locale: "en_IN",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "AI Jewellery Photoshoot Generator for Indian Jewellery Brands",
    description:
      "Bridal, diamond, kundan, pearls — editorial-grade jewellery photoshoots generated by AI in 60 seconds.",
    images: ["/banner1.png"],
  },
};

// ============================================================
// JSON-LD: Service + AggregateRating + Reviews + Breadcrumb
// ============================================================
const serviceSchema = {
  "@context": "https://schema.org",
  "@type": "Service",
  name: "Jewellery AI Studio",
  alternateName: "AI Jewellery Photoshoot Generator",
  description:
    "AI service for jewellery photoshoots — bridal sets, diamond rings, necklaces, earrings, kundan and pearls. Editorial-grade catalogue images in 60 seconds.",
  provider: {
    "@type": "Organization",
    name: "AgentForge AI",
    url: SITE,
  },
  areaServed: { "@type": "Country", name: "India" },
  serviceType: "AI Jewellery Photoshoot Generation",
  url: `${SITE}/jewellery-ai`,
  image: `${SITE}/logo-new.jpg`,
  offers: {
    "@type": "Offer",
    priceCurrency: "INR",
    price: "1999",
    url: `${SITE}/pricing`,
    availability: "https://schema.org/InStock",
  },
  // NOTE: aggregateRating / review were removed on purpose. The values
  // were hardcoded, not taken from real customer reviews, which breaks
  // Google's review-snippet rules. Add them back only when they are
  // computed from approved testimonials in the database.
};

const breadcrumbSchema = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "Home", item: SITE },
    {
      "@type": "ListItem",
      position: 2,
      name: "Jewellery AI Studio",
      item: `${SITE}/jewellery-ai`,
    },
  ],
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(serviceSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />
      {children}
    </>
  );
}
